# Generated by Django 5.2.3 on 2025-06-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('evento', models.CharField(max_length=100)),
                ('deporte', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('deporte', models.CharField(max_length=100)),
                ('hora', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('deporte', models.CharField(max_length=100)),
                ('cultura', models.CharField(max_length=100)),
                ('recreacion', models.CharField(max_length=100)),
                ('unico', models.ManyToManyField(to='pepe.entrenador')),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancha', models.CharField(max_length=100)),
                ('deporte', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(verbose_name=True)),
                ('us', models.ManyToManyField(to='pepe.actividades')),
                ('uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pepe.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=100)),
                ('deporte', models.CharField(max_length=100)),
                ('vario', models.ManyToManyField(to='pepe.actividades')),
            ],
        ),
    ]
